version: "3"

services:
  api:
    build: ./api/node-server
    command: npm run start
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - "80:80" # API is listening on port 80
    networks:
      - front-tier
      - back-tier
    environment:
      - PORT=80 # Port for Node.js to listen on
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker_postgres
      - POSTGRES_ADMIN_USER=admin_user
      - POSTGRES_ADMIN_PASSWORD=admin_password
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ocp
      - POSTGRES_MAX_CLIENT=10
      - POSTGRES_IDLE_TIMEOUT_MILLIS=30000

  db:
    #image: postgres:latest
    build: ./db
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker_postgres
      - POSTGRES_DB=ocp

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
