/**
 * Open City Project API
 * Interact with your city with the Open City Project API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenCityProjectApi);
  }
}(this, function(expect, OpenCityProjectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenCityProjectApi.UserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserApi', function() {
    describe('userDELETE', function() {
      it('should call userDELETE successfully', function(done) {
        //uncomment below and update the code to test userDELETE
        //instance.userDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userGET', function() {
      it('should call userGET successfully', function(done) {
        //uncomment below and update the code to test userGET
        //instance.userGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPATCH', function() {
      it('should call userPATCH successfully', function(done) {
        //uncomment below and update the code to test userPATCH
        //instance.userPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPOST', function() {
      it('should call userPOST successfully', function(done) {
        //uncomment below and update the code to test userPOST
        //instance.userPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userStateAllGET', function() {
      it('should call userStateAllGET successfully', function(done) {
        //uncomment below and update the code to test userStateAllGET
        //instance.userStateAllGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userTypeAllGET', function() {
      it('should call userTypeAllGET successfully', function(done) {
        //uncomment below and update the code to test userTypeAllGET
        //instance.userTypeAllGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersAllGET', function() {
      it('should call usersAllGET successfully', function(done) {
        //uncomment below and update the code to test usersAllGET
        //instance.usersAllGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
