/**
 * Open City Project API
 * Interact with your city with the Open City Project API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenCityProjectApi);
  }
}(this, function(expect, OpenCityProjectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenCityProjectApi.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be.a(OpenCityProjectApi.User);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property oauthProvider (base name: "oauth_provider")', function() {
      // uncomment below and update the code to test the property oauthProvider
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property oauthToken (base name: "oauth_token")', function() {
      // uncomment below and update the code to test the property oauthToken
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

    it('should have the property oauthTokenExpiration (base name: "oauth_token_expiration")', function() {
      // uncomment below and update the code to test the property oauthTokenExpiration
      //var instane = new OpenCityProjectApi.User();
      //expect(instance).to.be();
    });

  });

}));
